# encoding=utf-8

import django.test as unittest
import StringIO
import datetime
from ingredients.management.faq import FaqDataFromCsv

# * As many questions and answers are created as there are CSV rows.
# * Each CVS row should create appropriate question and answer models.
# * A created question and answer should each be attached to the correct user.
# * As many FAQs are created as unique URLs.
# * Eash FAQ has the correct number of items.

class TestFaqData(unittest.TestCase):
    
#    def test_as_many_Qs_and_As_are_created_as_there_are_csv_rows(self):
#        
#        num_qs = 0
#        num_as = 0
#        
#        num_csv_rows = 0
#        
#        self.assertEqual(num_qs, num_as)
#        self.assertEqual(num_as, num_csv_rows)
    
    def setUp(self):
        from forum.models import User
        
        users = User.objects.all()
        if len(users) > 0:
            return
        
        print 'creating user...'
        user = User(
            is_approved = True,
            email_isvalid = True,

            reputation = 1,
            gold = 0,
            silver = 0,
            bronze = 0,

            last_seen = '2011-02-24',
            real_name = 'my name',
            website = '',
            location = '',
            date_of_birth = '1983-12-06',
            about = ''
        )
        user.save()
        print 'user: %s' % user
        
    def test_each_faq_has_the_correct_number_of_items(self):
        criteria = [
            ('http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf', 10),
            ('http://www.seattle.gov/cable/faq.htm', 13)
        ]
        
        csv_stream = StringIO.StringIO(const.csv_data)
        
        faq_data = FaqDataFromCsv(csv_stream)
        faqs = faq_data.save()
        
        for url, count in criteria:
            for faq in faqs:
                if faq.url == url:
                    self.assertEqual(len(faq.items.all()), count)
                    break
    
    def test_as_many_faqs_are_created_as_unique_urls(self):
        csv_stream = StringIO.StringIO(const.csv_data)
        
        faq_data = FaqDataFromCsv(csv_stream)
        faqs = faq_data.save()
        
        num_faqs_created = len(faqs)
        num_unique_urls = 3
        
        self.assertEqual(num_faqs_created, num_unique_urls)
        

class const(object):
    csv_data = '''"url","createDate","questionNumber","question","answer"
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","1","Where does the Office of Arts & Cultural Affairs get its funding?","Currently, the department’s 2009 budget includes $2.9 million from the city’s general fund; nearly $1.2 million in city-admission-tax revenue; and $2.8 million from the municipal arts fund, which sets aside 1 percent of the cost of city building projects for public art – for a total agency budget of $6.9 million in 2009."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","2","What is the city of Seattle admission tax?","The city of Seattle collects 5 percent on every dollar of ticket sales to entertainment and recreational events, including movies, rock concerts and University of Washington football games. Nonprofit cultural organizations and some live music venues don’t pay the tax. Currently, the Office of Arts & Cultural Affairs receives 20 percent of admission- tax revenues. In recent years, the department’s portion of the revenue has been based on roughly $5 million in eligible admission-tax receipts, resulting in an annual allocation ranging from $1 to $1.2 million."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","3","Why shift to admission-tax revenue as the primary funding source?","In his 2010 budget, Mayor Greg Nickels proposed sending 75 percent of city admission-tax-revenues to the Office of Arts & Cultural Affairs – shifting more than half of the department’s budget from the city’s general fund to admission-tax revenue. Increasing the percentage of a dedicated funding source – especially in these difficult economic times – emphasizes the importance of arts and culture to Seattle’s economy and to our quality of life. With the nexus between admission tax dollars and arts and culture already well established, this is a vote of confidence by city leaders in the value of our arts and culture sector. The remaining 25 percent of admission-tax receipts the city collects will go to the general fund."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","4","Why change the funding stream for arts now?","This is a challenging time for government at every level to provide essential services. Admission-tax revenue provides a dedicated and reliable funding stream for the Office of Arts & Cultural Affairs and buffers the department from the year-to-year variability of the general fund. Shifting the department from the general fund to admission-tax revenue will secure a dedicated funding source for arts and help the city hold the line on current funding levels for arts and culture. This is welcome news, as most of Seattle’s arts and cultural organizations have suffered significant losses in endowments and contributed revenue."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","5","Will a dedicated funding source for arts affect other city programs?","No. This move is budget neutral and won’t result in cuts to other city programs. Currently, the bulk of admission-tax revenue goes to the city’s general fund. To offset its increased percentage of admission tax, the department will take an equivalent reduction in its current general fund allocation."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","6","Is admission-tax revenue a stable funding source?","Yes. Over the past decade, admission-tax revenue has remained fairly steady, showing modest growth in most years. This does not mean there aren’t fluctuations in the tax. But variations have been relatively minor as compared with the general fund over the same period. In fact, motion picture attendance, which is one source of admission-tax revenue, historically increases during a recession."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","7","Does this prohibit the Office from receiving other city funds?","No. As a city department, the Office could receive general fund appropriations for special projects and initiatives in the future."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","8","Why dedicate funding for the arts during a recession?","The arts are an important part of our economy. Investing in the arts in troubled times fuels the economy and creates a better environment in which our communities can thrive. Investment in the arts made a difference in another difficult financial era, and programs like the Federal Arts Project and the Works Progress Administration helped America emerge from the Great Depression and left us with some lasting cultural and artistic legacies."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","9","What about future economic downturns?","The mayor’s proposal calls for a reserve of admission-tax dollars to cushion the Office against economic downturns or a dip in tax revenue. The department’s annual admission-tax allocation will be based on receipts from two years prior. For 2010, the calculation will be based on 75 percent of eligible receipts collected in 2008. Next year, this will amount to $3.6 million in tax revenue for the Office. With a dedicated revenue stream that is based on previous year’s receipts, we will be able to anticipate and plan for downward trends."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","10","Will this impact the department’s place in city government?","No. The Office of Arts & Cultural Affairs will remain an executive city department, accountable to the mayor, City Council and the citizens of Seattle. The agency will continue to work with city leaders to integrate arts and culture in the work of the city and promote Seattle’s vibrant arts and cultural resources."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","1","Where does the Office of Arts & Cultural Affairs get its funding?","Currently, the department’s 2009 budget includes $2.9 million from the city’s general fund; nearly $1.2 million in city-admission-tax revenue; and $2.8 million from the municipal arts fund, which sets aside 1 percent of the cost of city building projects for public art – for a total agency budget of $6.9 million in 2009."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","2","What is the city of Seattle admission tax?","The city of Seattle collects 5 percent on every dollar of ticket sales to entertainment and recreational events, including movies, rock concerts and University of Washington football games. Nonprofit cultural organizations and some live music venues don’t pay the tax. Currently, the Office of Arts & Cultural Affairs receives 20 percent of admission- tax revenues. In recent years, the department’s portion of the revenue has been based on roughly $5 million in eligible admission-tax receipts, resulting in an annual allocation ranging from $1 to $1.2 million."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","3","Why shift to admission-tax revenue as the primary funding source?","In his 2010 budget, Mayor Greg Nickels proposed sending 75 percent of city admission-tax-revenues to the Office of Arts & Cultural Affairs – shifting more than half of the department’s budget from the city’s general fund to admission-tax revenue. Increasing the percentage of a dedicated funding source – especially in these difficult economic times – emphasizes the importance of arts and culture to Seattle’s economy and to our quality of life. With the nexus between admission tax dollars and arts and culture already well established, this is a vote of confidence by city leaders in the value of our arts and culture sector. The remaining 25 percent"
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","4","Why change the funding stream for arts now?","This is a challenging time for government at every level to provide essential services. Admission-tax revenue provides a dedicated and reliable funding stream for the Office of Arts & Cultural Affairs and buffers the department from the year-to-year variability of the general fund. Shifting the department from the general fund to admission-tax revenue will secure a dedicated funding source for arts and help the city hold the line on current funding levels for arts and culture. This is welcome news, as most of Seattle’s arts and cultural organizations have suffered significant losses in endowments and contributed revenue."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","5","Will a dedicated funding source for arts affect other city programs?","No. This move is budget neutral and won’t result in cuts to other city programs. Currently, the bulk of admission-tax revenue goes to the city’s general fund. To offset its increased percentage of admission tax, the department will take an equivalent reduction in its current general fund allocation."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","6","Is admission-tax revenue a stable funding source?","Yes. Over the past decade, admission-tax revenue has remained fairly steady, showing modest growth in most years. This does not mean there aren’t fluctuations in the tax. But variations have been relatively minor as compared with the general fund over the same period. In fact, motion picture attendance, which is one source of admission-tax revenue, historically increases during a recession."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","7","Does this prohibit the Office from receiving other city funds?","No. As a city department, the Office could receive general fund appropriations for special projects and initiatives in the future"
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","8","Why dedicate funding for the arts during a recession?","The arts are an important part of our economy. Investing in the arts in troubled times fuels the economy and creates a better environment in which our communities can thrive. Investment in the arts made a difference in another difficult financial era, and programs like the Federal Arts Project and the Works Progress Administration helped America emerge from the Great Depression and left us with some lasting cultural and artistic legacies."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","9","What about future economic downturns?","The mayor’s proposal calls for a reserve of admission-tax dollars to cushion the Office against economic downturns or a dip in tax revenue. The department’s annual admission-tax allocation will be based on receipts from two years prior. For 2010, the calculation will be based on 75 percent of eligible receipts collected in 2008. Next year, this will amount to $3.6 million in tax revenue for the Office. With a dedicated revenue stream that is based on previous year’s receipts, we will be able to anticipate and plan for downward trends."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","10","Will this impact the department’s place in city government?","No. The Office of Arts & Cultural Affairs will remain an executive city department, accountable to the mayor, City Council and the citizens of Seattle. The agency will continue to work with city leaders to integrate arts and culture in the work of the city and promote Seattle’s vibrant arts and cultural resources."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","1","Where does the Office of Arts & Cultural Affairs get its funding?","Currently, the department’s 2009 budget includes $2.9 million from the city’s general fund; nearly $1.2 million in city-admission-tax revenue; and $2.8 million from the municipal arts fund, which sets aside 1 percent of the cost of city building projects for public art – for a total agency budget of $6.9 million in 2009."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","2","What is the city of Seattle admission tax?","The city of Seattle collects 5 percent on every dollar of ticket sales to entertainment and recreational events, including movies, rock concerts and University of Washington football games. Nonprofit cultural organizations and some live music venues don’t pay the tax. Currently, the Office of Arts & Cultural Affairs receives 20 percent of admission- tax revenues. In recent years, the department’s portion of the revenue has been based on roughly $5 million in eligible admission-tax receipts, resulting in an annual allocation ranging from $1 to $1.2 million."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","3","Why shift to admission-tax revenue as the primary funding source?","In his 2010 budget, Mayor Greg Nickels proposed sending 75 percent of city admission-tax-revenues to the Office of Arts & Cultural Affairs – shifting more than half of the department’s budget from the city’s general fund to admission-tax revenue. Increasing the percentage of a dedicated funding source – especially in these difficult economic times – emphasizes the importance of arts and culture to Seattle’s economy and to our quality of life. With the nexus between admission tax dollars and arts and culture already well established, this is a vote of confidence by city leaders in the value of our arts and culture sector. The remaining 25 percent of admission-tax receipts the city collects will go to the general fund."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","4","Why change the funding stream for arts now?","This is a challenging time for government at every level to provide essential services. Admission-tax revenue provides a dedicated and reliable funding stream for the Office of Arts & Cultural Affairs and buffers the department from the year-to-year variability of the general fund. Shifting the department from the general fund to admission-tax revenue will secure a dedicated funding source for arts and help the city hold the line on current funding levels for arts and culture. This is welcome news, as most of Seattle’s arts and cultural organizations have suffered significant losses in endowments and contributed revenue."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","5","Will a dedicated funding source for arts affect other city programs?","No. This move is budget neutral and won’t result in cuts to other city programs. Currently, the bulk of admission-tax revenue goes to the city’s general fund. To offset its increased percentage of admission tax, the department will take an equivalent reduction in its current general fund allocation."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","6","Is admission-tax revenue a stable funding source?","Yes. Over the past decade, admission-tax revenue has remained fairly steady, showing modest growth in most years. This does not mean there aren’t fluctuations in the tax. But variations have been relatively minor as compared with the general fund over the same period. In fact, motion picture attendance, which is one source of admission-tax revenue, historically increases during a recession."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","7","Does this prohibit the Office from receiving other city funds?","No. As a city department, the Office could receive general fund appropriations for special projects and initiatives in the future."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","8","Why dedicate funding for the arts during a recession?","The arts are an important part of our economy. Investing in the arts in troubled times fuels the economy and creates a better environment in which our communities can thrive. Investment in the arts made a difference in another difficult financial era, and programs like the Federal Arts Project and the Works Progress Administration helped America emerge from the Great Depression and left us with some lasting cultural and artistic legacies."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","9","What about future economic downturns?","The mayor’s proposal calls for a reserve of admission-tax dollars to cushion the Office against economic downturns or a dip in tax revenue. The department’s annual admission-tax allocation will be based on receipts from two years prior. For 2010, the calculation will be based on 75 percent of eligible receipts collected in 2008. Next year, this will amount to $3.6 million in tax revenue for the Office. With a dedicated revenue stream that is based on previous year’s receipts, we will be able to anticipate and plan for downward trends."
"http://www.seattle.gov/arts/_downloads/admission_tax_faqs.pdf","Wed Apr 27 21:14:22 GMT 2011","10","Will this impact the department’s place in city government?","No. The Office of Arts & Cultural Affairs will remain an executive city department, accountable to the mayor, City Council and the citizens of Seattle. The agency will continue to work with city leaders to integrate arts and culture in the work of the city and promote Seattle’s vibrant arts and cultural resources."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","1","If my organization is more than three years old, can I apply?","No matter what your organization's age, you may apply if your group is not currently funded by our "Civic Partners,"" ""Youth Arts"" or ""Neighborhood and Community Arts"" funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","2","I'm under the age of 18. Can I apply?","Yes. We are happy to receive project ideas from young people! But you will need an adult who can sign the contracts and receive the funds on your behalf."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","3","What if my project takes place in Seattle, but I or my group is based outside of Seattle?","If you are based just outside the city of Seattle but your project or event will take place in Seattle and will benefit Seattle residents, you may still be eligible to apply. Please bring this issue to the attention of staff in your initial conversation. If you are out-of-state or not based in the greater Seattle area, you are not eligible to apply, even if your project will take place in Seattle."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","4","Are all criteria for funding weighed equally?","Yes. Priority consideration will be given to projects that serve or represent underserved communities and / or are not eligible for our other funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","5","What do you mean by underserved community?","Any community that might not have as much access to cultural opportunities due to age, geography, ethnicity, physical differences, income or other barriers. The more you can demonstrate why the communities you represent or plan to target are underserved and how your project will benefit those communities, the more competitive your application will be."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","6","Do I have to have a business license to apply?","No. But if your project is approved, you will need a city of Seattle business license to receive funding. For information on getting a business license in Seattle, call (206) 684-8484 or go here. You may include this cost in your budget."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","7","Whose contact information should be listed in the grant?","Please provide contact information for the person who can best represent the project and take responsibility for making sure the project is completed and paperwork is submitted."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","8","Who is considered the "Authorized Representive""?","The person who is willing to sign all documents and take responsibility for the money if awarded."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","9","What happens if I receive an award amount less than I requested and then can't do my project?","Discuss this with a project manager. We know you may need to make changes. If the project cannot be completed with a partial amount and no other funding option is available, you can decline the award."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","10","If funded, how soon will I get payment?","City funding is awarded after your project is completed. Expect payment three to four weeks after all required documents, including your final invoice and report, have been received by our office. Missing documents or incomplete paperwork can delay payment."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","1","If my organization is more than three years old, can I apply?","No matter what your organization's age, you may apply if your group is not currently funded by our "Civic Partners,"" ""Youth Arts"" or ""Neighborhood and Community Arts"" funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","2","I'm under the age of 18. Can I apply?","Yes. We are happy to receive project ideas from young people! But you will need an adult who can sign the contracts and receive the funds on your behalf."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","3","What if my project takes place in Seattle, but I or my group is based outside of Seattle?","If you are based just outside the city of Seattle but your project or event will take place in Seattle and will benefit Seattle residents, you may still be eligible to apply. Please bring this issue to the attention of staff in your initial conversation. If you are out-of-state or not based in the greater Seattle area, you are not eligible to apply, even if your project will take place in Seattle."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","4","Are all criteria for funding weighed equally?","Yes. Priority consideration will be given to projects that serve or represent underserved communities and / or are not eligible for our other funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","5","What do you mean by underserved community?","Any community that might not have as much access to cultural opportunities due to age, geography, ethnicity, physical differences, income or other barriers. The more you can demonstrate why the communities you represent or plan to target are underserved and how your project will benefit those communities, the more competitive your application will be."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","6","Do I have to have a business license to apply?","No. But if your project is approved, you will need a city of Seattle business license to receive funding. For information on getting a business license in Seattle, call (206) 684-8484 or go here. You may include this cost in your budget."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","7","Whose contact information should be listed in the grant?","Please provide contact information for the person who can best represent the project and take responsibility for making sure the project is completed and paperwork is submitted."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","8","Who is considered the "Authorized Representive""?","The person who is willing to sign all documents and take responsibility for the money if awarded."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","9","What happens if I receive an award amount less than I requested and then can't do my project?","Discuss this with a project manager. We know you may need to make changes. If the project cannot be completed with a partial amount and no other funding option is available, you can decline the award."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","10","If funded, how soon will I get payment?","City funding is awarded after your project is completed. Expect payment three to four weeks after all required documents, including your final invoice and report, have been received by our office. Missing documents or incomplete paperwork can delay payment."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","1","If my organization is more than three years old, can I apply?","No matter what your organization's age, you may apply if your group is not currently funded by our "Civic Partners,"" ""Youth Arts"" or ""Neighborhood and Community Arts"" funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","2","I'm under the age of 18. Can I apply?","Yes. We are happy to receive project ideas from young people! But you will need an adult who can sign the contracts and receive the funds on your behalf."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","3","What if my project takes place in Seattle, but I or my group is based outside of Seattle?","If you are based just outside the city of Seattle but your project or event will take place in Seattle and will benefit Seattle residents, you may still be eligible to apply. Please bring this issue to the attention of staff in your initial conversation. If you are out-of-state or not based in the greater Seattle area, you are not eligible to apply, even if your project will take place in Seattle."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","4","Are all criteria for funding weighed equally?","Yes. Priority consideration will be given to projects that serve or represent underserved communities and / or are not eligible for our other funding programs."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","5","What do you mean by underserved community?","Any community that might not have as much access to cultural opportunities due to age, geography, ethnicity, physical differences, income or other barriers. The more you can demonstrate why the communities you represent or plan to target are underserved and how your project will benefit those communities, the more competitive your application will be."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","6","Do I have to have a business license to apply?","No. But if your project is approved, you will need a city of Seattle business license to receive funding. For information on getting a business license in Seattle, call (206) 684-8484 or go here. You may include this cost in your budget."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","7","Whose contact information should be listed in the grant?","Please provide contact information for the person who can best represent the project and take responsibility for making sure the project is completed and paperwork is submitted."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","8","Who is considered the "Authorized Representive""?","The person who is willing to sign all documents and take responsibility for the money if awarded."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","9","What happens if I receive an award amount less than I requested and then can't do my project?","Discuss this with a project manager. We know you may need to make changes. If the project cannot be completed with a partial amount and no other funding option is available, you can decline the award."
"http://www.seattle.gov/arts/funding/smart_ventures_faq.asp","Wed Apr 27 21:14:22 GMT 2011","10","If funded, how soon will I get payment?","City funding is awarded after your project is completed. Expect payment three to four weeks after all required documents, including your final invoice and report, have been received by our office. Missing documents or incomplete paperwork can delay payment."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","1","How do I contact my cable company?","You may reach Comcast by calling 1-888-262-6300.  You may reach Millennium Digital Media by calling 1-800-829-2225."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","2","How to I resolve issues with my cable company?","First, contact your cable company at the number listed above.  Be courteous and state the facts briefly, providing any additional information which supports your position.  It will be helpful if you have your account number, copies of bills, receipts, cancelled checks, letters, and company notices – anything which supports your position.      When talking to your cable company, be sure to get the name of the people you talk with and keep copies of any correspondence from them.  If you are sending a complaint by mail, do not send it with your bill and make sure you send it to the address listed on the top of the bill.  Please do not send it to the City, as this will slow down any response.     Be very specific about what it is you are asking about.  If you have more than one question or complaint, right them down so you cover them all.  Also be specific about what it is you are asking your cable company to do: whether you are calling about a service call or a credit, tell them directly.     If you do not receive a satisfactory response, ask to speak with a supervisor.  This is your right.  If you are still not satisfied, you may contact us at the Office of Cable Communications for assistance.  You may email a complaint to www.cityofseattle.net/cable/comment or call our hotline at 206-684-8498.  Please be sure to include your name, the name of the person on the account, your telephone number on the account, and the address.  Describe the problem clearly."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","3","My bill shows a “franchise fee.”  What is this?","The City of Seattle charges your cable company a franchise fee to use the public rights-of-way for private enterprise.  The franchise fee is five percent of the company’s gross revenue, and is used to support the Seattle channel, community technology initiatives, the Citizens’ Technology and Telecommunications Advisory Board, and this Office of Cable Communications."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","4","What are the different cable services I can get in Seattle?","That depends on your cable company, although both Broadstripe and Comcast provide the full range of television and Internet cable services.  Comcast provides Limited Basic, Expanded Basic, Digital TV/radio, and cable modem Internet.  Millennium provides Expanded Basic and Digital TV/radio and cable modem Internet.  Both companies offer programming packages as well as pay per view opportunities.vvvvv"
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","5","Who regulates cable rates?","These levels of service include all program channels on the system other than basic service such as CNN, Showtime and pay-per-view. Rates for this level Basic Service Regulations The City of Seattle has limited authority to regulate rates for basic cable service, installation, and service charges related to basic service, including the ability to review FCC rate filings by Comcast to ensure that the filings are prepared in accordance with FCC guidelines. The City does not have the ability to regulate any rates for Broadstripe due to their federal classification as a small cable operator. Basic service is the lowest level of cable service a subscriber can buy. It includes, at a minimum, all over-the-air television broadcast signals carried pursuant to the FCC must-carry rules, and any public, educational or government access channels required by the cable operator's franchise. Expanded Basic / All other Tiers of Service Regulations These levels of service include all program channels on the system other than basic service such as CNN, Showtime and pay-per-view. Rates for this level of programming are no longer regulated by the FCC or the local franchise authority as of March 31, 1999."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","6","Are there discounts for senior citizens or disabled people?","Yes. Comcast provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. Millennium Digital Media also provides provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. For more information, you may contact Comcast at 1-888-262-6300 or Broadstripe at 1-800-829-2225. Seniors may also contact the Mayor's Office for Senior Citizens at 684-0500 for information regarding cable discounts and other senior benefits in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","7","Does Seattle have any consumer protection standards to help me with my cable company?c","Yes.  Seattle has the Cable Customer Bill of Rights (CCBOR), adopted in 1999, which established standards for cable companies and procedures and standards if those standards are not met.  Amended in 2002, the CCBOR specifies, for example, that if you don’t get offered an installation or service appointment within one week, you are entitled to free installation or credit, depending upon the service provided.  The complete CCBOR may be downloaded here. If you prefer, we can send you a copy."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","8","Where can I pay my cable bill?","Please see the payment center page on this webiste for details on where to make cable service payments and drop off equipment. The City of Seattle does not accept cable payments or equipment."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","9","What regulations govern cable television in Seattle?","The City of Seattle has awarded franchises to two cable companies, Millennium Digital Media and Comcast.  To view their respective franchises, please go to the franchises webpage. The City's Cable Code (SMC Chapter 21.60) also provides regulations that govern cable television in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","10","Who should I contact if I have a complaint regarding a program on the Seattle Community Access Network (SCAN) on Channel 29/77?","You may call the Seattle Community Access Channel at 206-522-4758.     Public access provides citizens with a video “soapbox” to express themselves on whatever topic they choose, within a set of rules established by SCAN and applicable law.  As long as the producer stays within these standards, the program can continue to be broadcast.     Because the program producer enjoys rights under the First Amendment to the Constitution, programs are not previewed before they are broadcast.  SCAN’s rules, however, establish a process for reviewing a program if and when a complaint is received.  If you watch a program that you believe is objectionable, please contact SCAN at 522-4758 for information regarding how to file a complaint.  Your written complaint will trigger a review process. If the program is found to be obscene, that finding may result in a suspension of broadcast privileges for the program producer.     The City is not authorized to review program content on SCAN, therefore, it is best to contact SCAN directly regarding issues concerning programs you find objectionable."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","11","Can I block channels on my TV?","Yes, to block channels you do not want to watch, you may call your cable company and ask them to do it; use your converter box or remote “parent control feature,” or use your TV’s V-chip.  Your cable company should be able to help you with this process."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","12","Who regulates telephone services in the state of Washington?","The Washington Utilities and Telecommunications Commission (WUTC) regulates telephone services in the state of Washington. You make contact them with questions or complaints by calling 1-800-562-6150 or by email at consumer@wutc.wa.gov. You may also go to the WUTC website at www.wutc.wa.gov and click on "complaint form"" on the right hand side of the WUTC home page."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","13","How can I get cable information from the Federal Communications Commission (FCC)?","Cable Service Bureau Fact Sheets are available for viewing at the FCC web site, at http://www.fcc.gov/."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","1","How do I contact my cable company?","You may reach Comcast by calling 1-888-262-6300.  You may reach Millennium Digital Media by calling 1-800-829-2225."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","2","How to I resolve issues with my cable company?","First, contact your cable company at the number listed above.  Be courteous and state the facts briefly, providing any additional information which supports your position.  It will be helpful if you have your account number, copies of bills, receipts, cancelled checks, letters, and company notices – anything which supports your position.      When talking to your cable company, be sure to get the name of the people you talk with and keep copies of any correspondence from them.  If you are sending a complaint by mail, do not send it with your bill and make sure you send it to the address listed on the top of the bill.  Please do not send it to the City, as this will slow down any response.     Be very specific about what it is you are asking about.  If you have more than one question or complaint, right them down so you cover them all.  Also be specific about what it is you are asking your cable company to do: whether you are calling about a service call or a credit, tell them directly.     If you do not receive a satisfactory response, ask to speak with a supervisor.  This is your right.  If you are still not satisfied, you may contact us at the Office of Cable Communications for assistance.  You may email a complaint to www.cityofseattle.net/cable/comment or call our hotline at 206-684-8498.  Please be sure to include your name, the name of the person on the account, your telephone number on the account, and the address.  Describe the problem clearly."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","3","My bill shows a “franchise fee.”  What is this?","The City of Seattle charges your cable company a franchise fee to use the public rights-of-way for private enterprise.  The franchise fee is five percent of the company’s gross revenue, and is used to support the Seattle channel, community technology initiatives, the Citizens’ Technology and Telecommunications Advisory Board, and this Office of Cable Communications."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","4","What are the different cable services I can get in Seattle?","That depends on your cable company, although both Broadstripe and Comcast provide the full range of television and Internet cable services.  Comcast provides Limited Basic, Expanded Basic, Digital TV/radio, and cable modem Internet.  Millennium provides Expanded Basic and Digital TV/radio and cable modem Internet.  Both companies offer programming packages as well as pay per view opportunities."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","5","Who regulates cable rates?","Basic Service Regulations The City of Seattle has limited authority to regulate rates for basic cable service, installation, and service charges related to basic service, including the ability to review FCC rate filings by Comcast to ensure that the filings are prepared in accordance with FCC guidelines. The City does not have the ability to regulate any rates for Broadstripe due to their federal classification as a small cable operator. Basic service is the lowest level of cable service a subscriber can buy. It includes, at a minimum, all over-the-air television broadcast signals carried pursuant to the FCC must-carry rules, and any public, educational or government access channels required by the cable operator's franchise. Expanded Basic / All other Tiers of Service Regulations These levels of service include all program channels on the system other than basic service such as CNN, Showtime and pay-per-view. Rates for this level of programming are no longer regulated by the FCC or the local franchise authority as of March 31, 1999."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","6","Are there discounts for senior citizens or disabled people?","Yes. Comcast provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. Millennium Digital Media also provides provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. For more information, you may contact Comcast at 1-888-262-6300 or Broadstripe at 1-800-829-2225. Seniors may also contact the Mayor's Office for Senior Citizens at 684-0500 for information regarding cable discounts and other senior benefits in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","7","Yes. Comcast provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. Millennium Digital Media also provides provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing. For more information, you may contact Comcast at 1-888-262-6300 or Broadstripe at 1-800-829-2225. Seniors may also contact the Mayor's Office for Senior Citizens at 684-0500 for information regarding cable discounts and other senior benefits in Seattle.","Yes.  Seattle has the Cable Customer Bill of Rights (CCBOR), adopted in 1999, which established standards for cable companies and procedures and standards if those standards are not met.  Amended in 2002, the CCBOR specifies, for example, that if you don’t get offered an installation or service appointment within one week, you are entitled to free installation or credit, depending upon the service provided.  The complete CCBOR may be downloaded here. If you prefer, we can send you a copy."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","8","Where can I pay my cable bill?","Please see the payment center page on this webiste for details on where to make cable service payments and drop off equipment. The City of Seattle does not accept cable payments or equipment."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","9","What regulations govern cable television in Seattle?","The City of Seattle has awarded franchises to two cable companies, Millennium Digital Media and Comcast.  To view their respective franchises, please go to the franchises webpage. The City's Cable Code (SMC Chapter 21.60) also provides regulations that govern cable television in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","10","Who should I contact if I have a complaint regarding a program on the Seattle Community Access Network (SCAN) on Channel 29/77?","You may call the Seattle Community Access Channel at 206-522-4758.     Public access provides citizens with a video “soapbox” to express themselves on whatever topic they choose, within a set of rules established by SCAN and applicable law.  As long as the producer stays within these standards, the program can continue to be broadcast.     Because the program producer enjoys rights under the First Amendment to the Constitution, programs are not previewed before they are broadcast.  SCAN’s rules, however, establish a process for reviewing a program if and when a complaint is received.  If you watch a program that you believe is objectionable, please contact SCAN at 522-4758 for information regarding how to file a complaint.  Your written complaint will trigger a review process. If the program is found to be obscene, that finding may result in a suspension of broadcast privileges for the program producer.     The City is not authorized to review program content on SCAN, therefore, it is best to contact SCAN directly regarding issues concerning programs you find objectionable."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","11","Can I block channels on my TV?","Yes, to block channels you do not want to watch, you may call your cable company and ask them to do it; use your converter box or remote “parent control feature,” or use your TV’s V-chip.  Your cable company should be able to help you with this process."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","12","Who regulates telephone services in the state of Washington?","The Washington Utilities and Telecommunications Commission (WUTC) regulates telephone services in the state of Washington. You make contact them with questions or complaints by calling 1-800-562-6150 or by email at consumer@wutc.wa.gov. You may also go to the WUTC website at www.wutc.wa.gov and click on "complaint form"" on the right hand side of the WUTC home page."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","13","How can I get cable information from the Federal Communications Commission (FCC)?","Cable Service Bureau Fact Sheets are available for viewing at the FCC web site, at http://www.fcc.gov/."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","1","How do I contact my cable company?","You may reach Comcast by calling 1-888-262-6300.   You may reach Millennium Digital Media by calling 1-800-829-2225."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","2","How to I resolve issues with my cable company?","First, contact your cable company at the number listed above.  Be courteous and state the facts briefly, providing any additional information which supports your position.  It will be helpful if you have your account number, copies of bills, receipts, cancelled checks, letters, and company notices � anything which supports your position.   When talking to your cable company, be sure to get the name of the people you talk with and keep copies of any correspondence from them.  If you are sending a complaint by mail, do not send it with your bill and make sure you send it to the address listed on the top of the bill.  Please do not send it to the City, as this will slow down any response. Be very specific about what it is you are asking about.  If you have more than one question or complaint, right them down so you cover them all.  Also be specific about what it is you are asking your cable company to do: whether you are calling about a service call or a credit, tell them directly. If you do not receive a satisfactory response, ask to speak with a supervisor.  This is your right.  If you are still not satisfied, you may contact us at the Office of Cable Communications for assistance.  You may email a complaint to www.cityofseattle.net/cable/comment or call our hotline at 206-684-8498.  Please be sure to include your name, the name of the person on the account, your telephone number on the account, and the address.  Describe the problem clearly."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","3","My bill shows a �franchise fee.�  What is this?","The City of Seattle charges your cable company a franchise fee to use the public rights-of-way for private enterprise.  The franchise fee is five percent of the company�s gross revenue, and is used to support the Seattle channel, community technology initiatives, the Citizens� Technology and Telecommunications Advisory Board, and this Office of Cable Communications."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","4","What are the different cable services I can get in Seattle?","That depends on your cable company, although both Broadstripe and Comcast provide the full range of television and Internet cable services.  Comcast provides Limited Basic, Expanded Basic, Digital TV/radio, and cable modem Internet.  Millennium provides Expanded Basic and Digital TV/radio and cable modem Internet.  Both companies offer programming packages as well as pay per view opportunities."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","5","Who regulates cable rates?","Basic Service Regulations The City of Seattle has limited authority to regulate rates for basic cable service, installation, and service charges related to basic service, including the ability to review FCC rate filings by Comcast to ensure that the filings are prepared in accordance with FCC guidelines. The City does not have the ability to regulate any rates for Broadstripe due to their federal classification as a small cable operator. Basic service is the lowest level of cable service a subscriber can buy. It includes, at a minimum, all over-the-air television broadcast signals carried pursuant to the FCC must-carry rules, and any public, educational or government access channels required by the cable operator's franchise.  Expanded Basic / All other Tiers of Service Regulations These levels of service include all program channels on the system other than basic service such as CNN, Showtime and pay-per-view. Rates for this level of programming are no longer regulated by the FCC or the local franchise authority as of March 31, 1999."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","6","Are there discounts for senior citizens or disabled people?","Yes. Comcast provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing.  Millennium Digital Media also provides provides a discount of approximately $4 off of the monthly rate for any tier of cable service for low income seniors, low income disabled, and people living in subsidized housing.  For more information, you may contact Comcast at 1-888-262-6300 or Broadstripe at 1-800-829-2225. Seniors may also contact the Mayor's Office for Senior Citizens at 684-0500 for information regarding cable discounts and other senior benefits in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","7","Does Seattle have any consumer protection standards to help me with my cable company?","Yes.  Seattle has the Cable Customer Bill of Rights (CCBOR), adopted in 1999, which established standards for cable companies and procedures and standards if those standards are not met.  Amended in 2002, the CCBOR specifies, for example, that if you don�t get offered an installation or service appointment within one week, you are entitled to free installation or credit, depending upon the service provided.  The complete CCBOR may be downloaded here. If you prefer, we can send you a copy."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","8","Where can I pay my cable bill?","Please see the payment center page on this webiste for details on where to make cable service payments and drop off equipment. The City of Seattle does not accept cable payments or equipment."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","9","What regulations govern cable television in Seattle?","The City of Seattle has awarded franchises to two cable companies, Millennium Digital Media and Comcast.  To view their respective franchises, please go to the franchises webpage. The City's Cable Code (SMC Chapter 21.60) also provides regulations that govern cable television in Seattle."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","10","Who should I contact if I have a complaint regarding a program on the Seattle Community Access Network (SCAN) on Channel 29/77?","You may call the Seattle Community Access Channel at 206-522-4758. Public access provides citizens with a video �soapbox� to express themselves on whatever topic they choose, within a set of rules established by SCAN and applicable law.  As long as the producer stays within these standards, the program can continue to be broadcast. Because the program producer enjoys rights under the First Amendment to the Constitution, programs are not previewed before they are broadcast.  SCAN�s rules, however, establish a process for reviewing a program if and when a complaint is received.  If you watch a program that you believe is objectionable, please contact SCAN at 522-4758 for information regarding how to file a complaint.  Your written complaint will trigger a review process. If the program is found to be obscene, that finding may result in a suspension of broadcast privileges for the program producer.  The City is not authorized to review program content on SCAN, therefore, it is best to contact SCAN directly regarding issues concerning programs you find objectionable."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","11","Can I block channels on my TV?","Yes, to block channels you do not want to watch, you may call your cable company and ask them to do it; use your converter box or remote �parent control feature,� or use your TV�s V-chip.  Your cable company should be able to help you with this process."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","12","Who regulates telephone services in the state of Washington?","The Washington Utilities and Telecommunications Commission (WUTC) regulates telephone services in the state of Washington. You make contact them with questions or complaints by calling 1-800-562-6150 or by email at consumer@wutc.wa.gov. You may also go to the WUTC website at www.wutc.wa.gov and click on "complaint form"" on the right hand side of the WUTC home page."
"http://www.seattle.gov/cable/faq.htm","Wed Apr 27 21:14:22 GMT 2011","13","How can I get cable information from the Federal Communications Commission (FCC)?","Cable Service Bureau Fact Sheets are available for viewing at the FCC web site, at http://www.fcc.gov/."'''
