<?php

/**
 * @file
 * A custom module for ET that defines blocks, probably for static content.
 * This will make it easier to have things in code.
 */
 
/**
 * Implements hook_block_info().
 */
function et_blocks_block_info() {
  $blocks['et_ph_organizers_count'] = array(
    'info' => t('Placeholder: Organizers count'),
  );
  $blocks['et_ph_volunteers_count'] = array(
    'info' => t('Placeholder: Volunteers count'),
  );
  $blocks['et_ph_projects_count'] = array(
    'info' => t('Placeholder: Projects count'),
  );
  $blocks['et_ph_clone_project'] = array(
    'info' => t('Placeholder: Clone Project'),
  );
  $blocks['et_ph_clone_recipe'] = array(
    'info' => t('Placeholder: Clone Recipe into Project'),
  );
  $blocks['et_custom_facebook_like'] = array(
    'info' => t('Custom: Facebook Like'),
  );
  $blocks['et_ph_project_supported'] = array(
    'info' => t('Placeholder: Project Supporter'),
  );
  $blocks['et_ph_project_location'] = array(
    'info' => t('Placeholder: Project Location'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function et_blocks_block_view($delta = '') {
  switch ($delta) {
    case 'et_ph_organizers_count':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('organizers_count');
      break;
      
    case 'et_ph_volunteers_count':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('volunteers_count');
      break;
      
    case 'et_ph_projects_count':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('projects_count');
      break;
      
    case 'et_ph_clone_project':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('clone_project');
      break;
      
    case 'et_ph_clone_recipe':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('clone_recipe');
      break;
      
    case 'et_ph_project_supported':
      $block['subject'] = '';
      $block['content'] = et_blocks_placeholder('project_supported');
      break;
      
    case 'et_ph_project_location':
      $block['subject'] = t('Location');
      $block['content'] = et_blocks_placeholder('project_location');
      break;
      
    case 'et_custom_facebook_like':
      $url = ($_SERVER['SERVER_PORT'] == '443') ? 'https' : 'http';
      $url .= '://';
      $url .= ($_SERVER['HTTP_HOST'] == 'localhost') ? 'localhost.com' : $_SERVER['HTTP_HOST'];
      $url .= $_SERVER['REQUEST_URI'];
      $block['subject'] = '';
      $block['content'] = '<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="' . urlencode($url) . '" send="true" width="200" show_faces="false" font=""></fb:like>';
      break;
  }
  return $block;
}

/**
 * Block placeholder content
 */
function et_blocks_placeholder($type) {
  $output = '';
  
  switch ($type) {
    case 'organizers_count':
      $output .= '
        <div class="category" id="category1">
          <span class="category_count">9</span>
          <span class="category_name">Organizers</span>
        </div>
      ';
      break;
      
    case 'volunteers_count':
      $output .= '
        <div class="category" id="category2">
          <span class="category_count">63</span>
          <span class="category_name">Volunteers</span>
        </div>
      ';
      break;
      
    case 'projects_count':
      $output .= '
        <div class="category" id="category3">
          <span class="category_count">17</span>
          <span class="category_name">Projects</span>
        </div>
      ';
      break;
      
    case 'clone_project':
      $output .= '
        <div class="ph-clone-project">
          ' . t('I want to fork this project.') . '
        </div>
      ';
      break;
      
    case 'project_supported':
      $output .= '
        <div class="ph-project-supported">
          <span class="supporters-numbers">
            ' . t('34') . '
          </span>
          <span class="supporters-label">
            ' . t('Supporters') . '
          </span>
          <span class="supporters-link">
            ' . l('Support this project', '') . '
          </span>
          
        </div>
      ';
      break;
      
    case 'project_location':
      $output .= '
        <div class="ph-project-location">
          <div id="project-map">
          </div>
          <div class="project-address">
            <span class="project-address-title">' . t('Parker Plaza') . '</span>
            ' . t('16th & Mission St.') . '<br />
            ' . t('San Francisco') . '
          </div>
        </div>
      ';
      break;
      
  }
  
  return $output;
}